/**
 * Cloudflare Worker — Nova Diagnostics
 *
 * Serves static assets from the Next.js `out/` directory.
 * Routes /r/* (secure report links with dynamic tokens) to the
 * pre-built shell page at /r/index.html (generated by trailingSlash: true),
 * which handles them client-side.
 * All other paths are served directly from static assets.
 */

interface Env {
  ASSETS: Fetcher;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    // /r/[token] — token is dynamic; serve the shell page that handles it client-side.
    // With trailingSlash: true, Next.js emits out/r/index.html — served at /r/index.html.
    // We pass a clean GET request so ASSETS.fetch never tries to clone a POST body.
    if (path.startsWith("/r/") && path.length > 3) {
      const shellUrl = new URL("/r/", url);
      try {
        return await env.ASSETS.fetch(shellUrl.toString());
      } catch {
        return new Response("Report page temporarily unavailable. Please try again.", {
          status: 503,
          headers: { "Content-Type": "text/plain" },
        });
      }
    }

    // Everything else — serve static file directly
    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;
